priceactionalerts/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dailycandle.urls', namespace='dailycandle')),
    path('account/', include('users.urls', namespace='users')),
    path('', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path,include
from users import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('register', views.register, name='register'),
    path('login',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('verify/<str:token>/',views.verify,name='verify'),


]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_token = models.CharField(max_length=200, blank=True)
    notification = models.BooleanField(default=True, blank=True)
    stocks = models.TextField(max_length=1000, blank=True)
    nudgedata = models.JSONField(null=True)

    def __str__(self):
        return f" {self.id}: {self.user} {self.notification} {self.stocks} {self.nudgedata}"

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .userform import CustomRegisterForm
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.models import User
from .models import *
from .emailactivation import *
import uuid

import pandas as pd
#import numpy as np
import yfinance as yf
from datetime import datetime, date, timedelta
import sys
import datetime, calendar
from collections import OrderedDict
from pytz import timezone
import time
import math

# Create your views here.


def register(request):

    if request.method=='POST':
        register_form = CustomRegisterForm(request.POST)
        username = request.POST['username']
        useremail = request.POST['email']
        userpassword = request.POST['password1']
        ind_time = datetime.datetime.now(timezone("Asia/Kolkata")).strftime('%Y-%m-%d')
        if register_form.is_valid():
            user = User.objects.create_user(username=username,email=useremail)
            user.set_password(userpassword)
            user.is_active=False
            user.save()
            email_token = str(uuid.uuid4())
            profile = Profile.objects.create(
                user=user,
                email_token=email_token,
                nudgedata={'nudgenotification':False,'maxloss': '', 'maxprofit': '', 'nudgeStockList': ['', '', '', '', '', '', '', '', '', ''],'nudgeStockListPrice': ['', '', '', '', '', '', '', '', '', '']},
            )
            #print("Register Profile:")
            send_email_token(useremail,profile.email_token)
            messages.success(request, "New Account Created. Check For Account Activation Email.")
            return redirect("users:login")

    else:
        register_form = CustomRegisterForm()
    return render(request, 'register.html',{'register_form': register_form})

def verify(request,token):
    try:
        profile_obj = Profile.objects.get(email_token = token)
        username = profile_obj.user
        user_obj = User.objects.get(username=username)
        user_obj.is_active=True
        user_obj.save()
        profile_obj.save()

        return redirect("users:login")

    except Exception as e:
        return HttpResponse("Invalid Token. Activation Failed.")

def login_view(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        #print("User: {} and {}. User: {}".format(username, password, user))
        if user is not None:
            login(request, user)
            profile_obj = Profile.objects.get(user = user)
            profile_stocks = profile_obj.stocks
            profile_notification = profile_obj.notification
            #print("Login User: {} and {}".format(profile_stocks,profile_notification))
            return redirect('dailycandle:index')
        else:
            messages.success(request, "Incorrect Username or Password")
            return render(request, 'login.html')

    else:
        return render(request, 'login.html')

def logout_view(request):
    logout(request)
    messages.success(request, "Logged Out !!!")
    return render(request, 'login.html')

users/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Price Action Alerts</title>

      <style>
          *{
             padding: 0;
             margin: 0;
             box-sizing: border-box;
           }
           body{
               background: rgb(245,245,245);

           }
           .row{
                background: white;
                border-radius: .3rem;
                box-shadow: 12px 12px 22px grey;
           }
           .btn1{
                border: none;
                outline: none;
                height: 50px;
                width: 100%;
                background-color: black;
                color: white;
                border-radius: 4px;
                font-weight: bold;
           }
           .btn1:hover{
                background: white;
                border: 1px solid;
                color: black;
           }

      </style>

  </head>
  <body>
    </br>
    <section class="Form mx-5 my-5">
        <div class="container">
            <div class="row no-gutters">
                <!--div class="col-lg-5 p-5 bg-primary text-white rounded-3" align="center"-->
                <div class="col-lg-5 p-5 text-white rounded-3" align="center" style="background-color: #0d6efd;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-activity" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z"/>
                    </svg>
                    <p><h1>PriceActionAlerts</h1></p>
                    <ul>
                        <h6 class= "mx-4" align="left"><li>Create a stock watchlist and get a weekly view dashboard of your watchlist</li></h6>
                        <h6 class= "mx-4" align="left"><li>Create a stock holdinglist and get alerted when your defined margin thresholds are met</li></h6>
                        <h6 class= "mx-4" align="left"><li>Know when the stock is in the Support or Resistance zone</li></h6>
                        <h6 class= "mx-4" align="left"><li>Get daily email update on the price action movement of your selected stocks</li></h6>
                        </br>
                        <h8 class= "mt-5" align="left" style="font-size:10px">** Price Action Alerts is not suitable for intraday trading</h8>

                    </ul>
                </div>
                <div class="col-lg-7 px-5 pt-5" align="center">
                    <!--h1 class="font-weight-bold py-3">Logo</h1-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
                      <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z"/>
                      <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    </svg>

                    {% if messages %}
                    {% for message in messages %}
                    <h4 class="font-weight-bold py-3">{{message}}</h4>
                    {% endfor %}
                    {% else %}
                    <h4 class="font-weight-bold py-3">Sign into your account</h4>
                    {% endif %}

                    <form action="{% url 'users:login' %}"  method="POST">
                        {% csrf_token%}
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="text" placeholder="Username (NOT Email)" class="form-control my-3 p-3", name="username">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                                <input type="password" placeholder="*******" class="form-control my-3 p-3", name="password">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-7">
                                <button type="submit" class="btn1 mb-5 mt-3">Login</button>
                            </div>
                        </div>
                        <a href="{% url 'users:password_reset' %}">Forgot Password</a>
                        <p>Don't have an account? <a href="{% url 'users:register' %}">SignUp</a></p>
                    </form>
                </div>
            </div>
        </div>
    </section>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

users/templates/prelogintemplate.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Price Action Alerts</title>
  </head>
  <body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->

    {% block body %}
    {% endblock body %}


  </body>
</html>

users/templates/register.html
{% extends 'prelogintemplate.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title xmlns="http://www.w3.org/1999/html">Account - Register</title>
{% endblock title %}


{% block body %}
  <div class="container mt-5">
  <p><h3>New Account Registration.....</h3></p>

      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}


      <form method="post" class="mt-5 col-6">
          {% csrf_token%}
          {{register_form|crispy}}
          <button type="submit" class="btn btn-primary mt-3">Register</button>
      </form>
  </div>



{% endblock body %}