dailycandle/urls.py
from django.urls import path
from . import views

app_name = "dailycandle"

urlpatterns = [
    path('', views.index, name="index"),
    path('profile', views.profile, name="profile"),
    path('holding', views.holding, name="holding"),
    path('metrics', views.metrics, name="metrics"),
    path('<str:id>/stockdetails', views.stockdetails, name="stockdetails"),

]   

priceactionalerts/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dailycandle.urls', namespace='dailycandle')),
    path('account/', include('users.urls', namespace='users')),
    path('', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path,include
from users import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('register', views.register, name='register'),
    path('login',views.login_view,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('verify/<str:token>/',views.verify,name='verify'),


]

dailycandle/views.py
from django.shortcuts import render,redirect
from users.models import *
from django.contrib import messages
from .models import *
from .form import *
from .emailnotification import *
from django.apps import apps
from django.contrib.auth.models import User

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, date, timedelta
import sys
import datetime, calendar
from collections import OrderedDict
from pytz import timezone
import time
import math
import re
from nsetools import Nse


companyicon = {
                    "NTPC":"https://logo.clearbit.com/ntpc.co.in",
                    "UPL": "https://logo.clearbit.com/upl-ltd.com",
                    "SUNPHARMA":"https://logo.clearbit.com/sunpharma.com",
                    "TATACONSUM": "https://logo.clearbit.com/tataconsumer.com",
                    "INDUSINDBK":"https://logo.clearbit.com/indusind.com",
                    "ONGC": "https://logo.clearbit.com/ongcindia.com",
                    "MM": "https://logo.clearbit.com/mahindra.com",
                    "IOC":"https://logo.clearbit.com/iocl.com",
                    "BHARTIARTL": "https://logo.clearbit.com/airtel.in",
                    "ITC":"https://logo.clearbit.com/itcportal.com",
                    "WIPRO": "https://logo.clearbit.com/wipro.com",
                    "TCS":"https://logo.clearbit.com/tcs.com",
                    "BRITANNIA": "https://logo.clearbit.com/britannia.co.in",
                    "COALINDIA":"https://logo.clearbit.com/coalindia.in",
                    "GRASIM": "https://logo.clearbit.com/grasim.com",
                    "TATAMOTORS":"https://logo.clearbit.com/tatamotors.com",
                    "TITAN": "https://logo.clearbit.com/titancompany.in",
                    "BPCL":"https://logo.clearbit.com/bharatpetroleum.com",
                    "JSWSTEEL": "https://logo.clearbit.com/jsw.in",
                    "INFY":"https://logo.clearbit.com/infosys.com",
                    "HDFC": "https://logo.clearbit.com/hdfc.com",
                    "DIVISLAB":"https://logo.clearbit.com/divislabs.com",
                    "SHREECEM": "https://logo.clearbit.com/shreecement.com",
                    "CIPLA":"https://logo.clearbit.com/cipla.com",
                    "ADANIPORTS": "https://logo.clearbit.com/adaniports.com",
                    "HCLTECH":"https://logo.clearbit.com/hcltech.com",
                    "HINDALCO": "https://logo.clearbit.com/hindalco.com",
                    "BAJFINANCE":"https://logo.clearbit.com/bajajfinserv.in",
                    "KOTAKBANK": "https://logo.clearbit.com/kotak.com",
                    "ASIANPAINT":"https://logo.clearbit.com/asianpaints.com",
                    "NESTLEIND": "https://logo.clearbit.com/nestle.in",
                    "HDFCLIFE":"https://logo.clearbit.com/hdfclife.com",
                    "ULTRACEMCO": "https://logo.clearbit.com/ultratechcement.com",
                    "RELIANCE":"https://logo.clearbit.com/ril.com",
                    "TATASTEEL": "https://logo.clearbit.com/tatasteel.com",
                    "HINDUNILVR":"https://logo.clearbit.com/hul.co.in",
                    "SBILIFE": "https://logo.clearbit.com/sbilife.co.in",
                    "LT":"https://logo.clearbit.com/larsentoubro.com",
                    "DRREDDY": "https://logo.clearbit.com/drreddys.com",
                    "HDFCBANK":"https://logo.clearbit.com/hdfcbank.com",
                    "EICHERMOT": "https://logo.clearbit.com/eichermotors.com",
                    "SBIN":"https://logo.clearbit.com/sbi.co.in",
                    "BAJAJFINSV": "https://logo.clearbit.com/bajajfinserv.in",
                    "AXISBANK":"https://logo.clearbit.com/axisbank.com",
                    "HEROMOTOCO": "https://logo.clearbit.com/heromotocorp.com",
                    "ICICIBANK":"https://logo.clearbit.com/icicibank.com",
                    "POWERGRID": "https://logo.clearbit.com/powergrid.in",
                    "TECHM":"https://logo.clearbit.com/techmahindra.com",
                    "MARUTI": "https://logo.clearbit.com/marutisuzuki.com",
    }


def index(request):
    if not request.user.is_authenticated:
        return redirect('users:login')

    else:
        try:
            finance = []
            stock_list = []
            profile_obj = Profile.objects.get(user=request.user)
            profile_stocks = profile_obj.stocks
            profile_stocks = profile_stocks.replace("[", "")
            profile_stocks = profile_stocks.replace("]", "")
            profile_stocks = profile_stocks.replace("'", "")
            profile_stocks = profile_stocks.replace(",", "")
            profile_notification = profile_obj.notification

            user_stock_list = profile_stocks.split()
            for stock in user_stock_list:
                pe = []
                data = []
                candle = []
                data.append(stock)
                stock = ''.join(e for e in stock if e.isalnum())
                data.append(companyicon[stock])
                new_stock_finance_comment = ""
                priceregex = r"Stock: 200DayAverage: ([a-zA-Z0-9.\s-]+)\(ie ([0-9.a-zA-Z]+)\)"
                rsiregex = r"Stock: Relative Strength Index: ([0-9]+)"
                peregex = r"Financial: Forward PE: ([0-9a-zA-Z]+)"

                Model = apps.get_model('dailycandle', stock)
                stockdb = Model.objects.get(id=1)
                stock_finance_comment = stockdb.Finance.split(", ")

                for i in stock_finance_comment:
                    i = i.replace("[", "")
                    i = i.replace("'", "")
                    i = i.replace("]", "")
                    new_stock_finance_comment += i
                    new_stock_finance_comment += ". "
                    if re.search(peregex, i):
                        match = re.search(peregex, i)
                        pe.append(match.group(1))
                finance.append(new_stock_finance_comment)

                stock_monday_comment = stockdb.Monday.split(", ")
                if len(stock_monday_comment) == 1:
                    data.append(" ")
                    data.extend((" "," "," "))
                for i in stock_monday_comment:
                    i = i.replace("[", "")
                    i = i.replace("'", "")
                    i = i.replace("]", "")
                    if re.search(priceregex, i):
                        match = re.search(priceregex, i)
                        data.append(match.group(2))
                    if re.search(rsiregex, i):
                        match = re.search(rsiregex, i)
                        data.append(match.group(1))
                        data.append(pe[0])
                    if ('Price Zone: INCONCLUSIVE' in i):
                        data.append("INCONCLUSIVE")
                    if ('Price Zone: In SUPPORT Zone' in i):
                        data.append("SUPPORT")
                    if ('Price Zone: In RESISTANCE Zone' in i):
                        data.append("RESISTANCE")

                stock_tuesday_comment = stockdb.Tuesday.split(", ")
                if len(stock_tuesday_comment) == 1:
                    data.append(" ")
                    data.extend((" "," "," "))
                for i in stock_tuesday_comment:
                    i = i.replace("[", "")
                    i = i.replace("'", "")
                    i = i.replace("]", "")
                    if re.search(priceregex, i):
                        match = re.search(priceregex, i)
                        data.append(match.group(2))
                    if re.search(rsiregex, i):
                        match = re.search(rsiregex, i)
                        data.append(match.group(1))
                        data.append(pe[0])
                    if ('Price Zone: INCONCLUSIVE' in i):
                        data.append("INCONCLUSIVE")
                    if ('Price Zone: In SUPPORT Zone' in i):
                        data.append("SUPPORT")
                    if ('Price Zone: In RESISTANCE Zone' in i):
                        data.append("RESISTANCE")

                stock_wednesday_comment = stockdb.Wednesday.split(", ")
                if len(stock_wednesday_comment) == 1:
                    data.append(" ")
                    data.extend((" "," "," "))
                for i in stock_wednesday_comment:
                    i = i.replace("[", "")
                    i = i.replace("'", "")
                    i = i.replace("]", "")
                    if re.search(priceregex, i):
                        match = re.search(priceregex, i)
                        data.append(match.group(2))
                    if re.search(rsiregex, i):
                        match = re.search(rsiregex, i)
                        data.append(match.group(1))
                        data.append(pe[0])

                    if ('Price Zone: INCONCLUSIVE' in i):
                        data.append("INCONCLUSIVE")
                    if ('Price Zone: In SUPPORT Zone' in i):
                        data.append("SUPPORT")
                    if ('Price Zone: In RESISTANCE Zone' in i):
                        data.append("RESISTANCE")

                stock_thursday_comment = stockdb.Thursday.split(", ")
                if len(stock_thursday_comment) == 1:
                    data.append(" ")
                    data.extend((" "," "," "))
                for i in stock_thursday_comment:
                    i = i.replace("[", "")
                    i = i.replace("'", "")
                    i = i.replace("]", "")
                    if re.search(priceregex, i):
                        match = re.search(priceregex, i)
                        data.append(match.group(2))
                    if re.search(rsiregex, i):
                        match = re.search(rsiregex, i)
                        data.append(match.group(1))
                        data.append(pe[0])

dailycandle/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!--script src="https://cdn.jsdelivr.net/npm/chart.js"></script-->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script-->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script-->

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>Price Action Alerts</title>
    <meta http-equiv="refresh" content="600">

    <style>
          *{
             padding: 0;
             margin: 0;
             box-sizing: border-box;
           }
           body{
               background: rgb(245,245,245);

           }
           .row{
                background: white;
                border-radius: .5rem;
                box-shadow: 12px 12px 22px grey;
           }
           .btn2{
                border: none;
                outline: none;
                height: 10px;
                width: 100%;
                background-color: black;
                color: white;
                border-radius: 4px;
                font-weight: bold;
           }
           .btn1:hover{
                background: white;
                border: 1px solid;
                color: black;
           }
           .table {
                border-collapse: separate;
                border-spacing:1 10px;
            }

      </style>

  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0d6efd;">
      <div class="container-fluid">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-activity" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z"/>
            </svg>
            <a class="navbar-brand mx-1" href="{% url 'dailycandle:index' %}"><h2>PriceActionAlerts...</h2></a>

        <div class="collapse navbar-collapse d-flex flex-row-reverse bd-highlight" id="navbarNavAltMarkup" >
          <div class="navbar-nav" >
            {% if request.user.username == 'admin' %}
            <a class="nav-link active" aria-current="page" href="{% url 'dailycandle:metrics' %}"><h5>Metrics</h5></a>
            {% endif %}
            <a class="nav-link active" aria-current="page" href="{% url 'dailycandle:index' %}"><h5>Watchlist</h5></a>
            <a class="nav-link active" aria-current="page" href="{% url 'dailycandle:holding' %}"><h5>Holding</h5></a>
            <a class="nav-link active" aria-current="page" href="{% url 'dailycandle:profile' %}"><h5>Profile</h5></a>
            <a href="{% url 'users:logout' %}">
            <button class="btn btn-light mx-3" type="submit"><h5>Logout</h5></button></a>
          </div>
        </div>
      </div>
    </nav>


  <div class="container my-5">
    <p><h1 class="mb-5" style="font-family:'Georgia, serif'">Watchlist Dashboard: Track Weekly Support & Resistance.</h1></p>
    {% if data %}
     <div class="row overflow-hidden">
     <table class="table table-hover align-middle mb-0 bg-white">
        <thead>
          <tr>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Stock</th>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Monday</th>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Tuesday</th>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Wednesday</th>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Thursday</th>
            <th scope="col" style="font-family:'Georgia, serif'; font-size:22px">Friday</th>
          </tr>
        </thead>

            {% if data %}
            {% for stocks in data %}

        <tbody>
          <tr>
            <th scope="row">
              <div class="d-flex align-items-center">
              <img src={{stocks.1}} alt="" style="width: 40px; height: 40px" class="rounded-circle" />
              <span class="btn1 badge bg-light text-dark"><a href="{% url 'dailycandle:stockdetails' stocks.0 %}"><p style="font-family:verdana" data-bs-toggle="tooltip" data-bs-html="true" title="click for more details">{{stocks.0}}</p></a></span>
              </div></th>

            {% if stocks.5 == 'SUPPORT' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.2}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.3}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.4}}</p>
              <span class="badge rounded-pill bg-success"><p style="font-size:10px">Zone: {{stocks.5}}</p></span></td>
            {% endif %}
            {% if stocks.5 == 'RESISTANCE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.2}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.3}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.4}}</p>
              <span class="badge rounded-pill bg-danger"><p style="font-size:10px">Zone: {{stocks.5}}</p></span></td>
            {% endif %}
            {% if stocks.5 == 'INCONCLUSIVE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.2}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.3}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.4}}</p>
              <p style="font-size:10px">Zone: {{stocks.5}}</p></td>
            {% endif %}
            {% if stocks.5 == ' ' %}
            <td><p style="font-size:10px"></p></td>
            {% endif %}
            {% if stocks.9 == 'SUPPORT' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.6}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.7}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.8}}</p>
              <span class="badge rounded-pill bg-success"><p style="font-size:10px">Zone: {{stocks.9}}</p></span></td>
            {% endif %}
            {% if stocks.9 == 'RESISTANCE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.6}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.7}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.8}}</p>
              <span class="badge rounded-pill bg-danger"><p style="font-size:10px">Zone: {{stocks.9}}</p></span></td>
            {% endif %}
            {% if stocks.9 == 'INCONCLUSIVE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.6}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.7}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.8}}</p>
              <p style="font-size:10px">Zone: {{stocks.9}}</p></td>
            {% endif %}
            {% if stocks.9 == ' ' %}
            <td><p style="font-size:10px"></p></td>
            {% endif %}
            {% if stocks.13 == 'SUPPORT' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.10}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.11}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.12}}</p>
              <span class="badge rounded-pill bg-success"><p style="font-size:10px">Zone: {{stocks.13}}</p></span></td>
            {% endif %}
            {% if stocks.13 == 'RESISTANCE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.10}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.11}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.12}}</p>
              <span class="badge rounded-pill bg-danger"><p style="font-size:10px">Zone: {{stocks.13}}</p></span></td>
            {% endif %}
            {% if stocks.13 == 'INCONCLUSIVE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.10}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.11}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.12}}</p>
              <p style="font-size:10px">Zone: {{stocks.13}}</p></td>
            {% endif %}
            {% if stocks.13 == ' ' %}
            <td><p style="font-size:10px"></p></td>
            {% endif %}
            {% if stocks.17 == 'SUPPORT' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.14}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.15}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.16}}</p>
              <span class="badge rounded-pill bg-success"><p style="font-size:10px">Zone: {{stocks.17}}</p></span></td>
            {% endif %}
            {% if stocks.17 == 'RESISTANCE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.14}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.15}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.16}}</p>
              <span class="badge rounded-pill bg-danger"><p style="font-size:10px">Zone: {{stocks.17}}</p></span></td>
            {% endif %}
            {% if stocks.17 == 'INCONCLUSIVE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.14}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.15}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.16}}</p>
              <p style="font-size:10px">Zone: {{stocks.17}}</p></td>
            {% endif %}
            {% if stocks.17 == ' ' %}
            <td><p style="font-size:10px"></p></td>
            {% endif %}
            {% if stocks.21 == 'SUPPORT' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.18}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.19}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.20}}</p>
              <span class="badge rounded-pill bg-success"><p style="font-size:10px">Zone: {{stocks.21}}</p></span></td>
            {% endif %}
            {% if stocks.21 == 'RESISTANCE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.18}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.19}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.20}}</p>
              <span class="badge rounded-pill bg-danger"><p style="font-size:10px">Zone: {{stocks.21}}</p></span></td>
            {% endif %}
            {% if stocks.21 == 'INCONCLUSIVE' %}
            <td>
              <p class="mx-2" style="font-size:10px">CMP: {{stocks.18}}</p>
              <p class="mx-2" style="font-size:10px">RSI: {{stocks.19}}</p>
              <p class="mx-2" style="font-size:10px">Forward PE: {{stocks.20}}</p>
              <p style="font-size:10px">Zone: {{stocks.21}}</p></td>
            {% endif %}
            {% if stocks.21 == ' ' %}
            <td><p style="font-size:10px"></p></td>
            {% endif %}

            {% endfor%}
            {% endif%}

          </tr>
        </tbody>
      </table>
    </div>
    {% else %}
    <p><h1 class="my-5" style="font-family:'Georgia, serif'">Welcome to PriceActionAlerts</h1></p>
    <p><h3 style="font-family:'Georgia, serif'">Currently you have not selected any stocks in the Watchlist. Can you add you preferred stocks from your account Profile page.</h3></p>
    {% endif%}

    </div>
  </br>


  </body>


</html>

dailycandle/templates/metrics.html
{% extends 'postlogintemplate.html' %}

{% block title %}
<title >Price Action Alerts</title>
{% endblock title %}

{% block body %}

<div class="container-fluid">
    <p class="mt-5" style="font-family:'Georgia, serif'"><h2>Number Of Total Users: {{users_count}}</h2></p>
    <p class="my-0" style="font-family:'Georgia, serif'"><h2>Number Of Users Who Have Enabled Watchlist Alert Notifiaction: {{watchlist_alert_count}}</h2></p>
    <p class="my-0" style="font-family:'Georgia, serif'"><h2>Number Of Users Who Have Enabled Holding Alert Notifiaction: {{holding_alert_count}}</h2></p>
    <p class="my-0" style="font-family:'Georgia, serif'"><h2>Last Login:</h2></p>
    <ul>
        {% for i,j in userlogin_count_by_days.items %}
        <p><li>{{i}} : {{j}}</li></p>
        {% endfor %}
    </ul>
</div>

{% endblock body %}